/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.justmejulian.gardena.mcp

import ch.justmejulian.gardena.mcp.server.MCPServer
import ch.justmejulian.gardena.mcp.service.GardenaService
import ch.justmejulian.gardena.mcp.util.Config
import kotlinx.coroutines.runBlocking

class App {
  suspend fun run() {
    try {
      // Load credentials from environment variables
      val credentials = Config.loadGardenaCredentials()
      val apiConfig = Config.loadApiConfig()

      // Create Gardena service
      val gardenaService =
        GardenaService(
          credentials.clientId,
          credentials.clientSecret,
          apiConfig.authBaseUrl,
          apiConfig.apiBaseUrl,
        )

      // Start MCP server - authentication will happen lazily on first tool call
      System.err.println("Starting MCP server...")
      val mcpServer = MCPServer(gardenaService)
      mcpServer.run()
    } catch (e: IllegalStateException) {
      System.err.println("Configuration Error: ${e.message}")
    } catch (e: Exception) {
      System.err.println("Error: ${e.message}")
      e.printStackTrace()
    }
  }
}

fun main() = runBlocking { App().run() }
