/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.justmejulian.gardena.mcp

import ch.justmejulian.gardena.mcp.client.GardenaService
import ch.justmejulian.gardena.mcp.util.Config
import kotlinx.coroutines.runBlocking

class App {
  suspend fun run() {
    try {
      // Load credentials from environment variables
      val credentials = Config.loadGardenaCredentials()
      val apiConfig = Config.loadApiConfig()

      // Create Gardena service
      val service =
        GardenaService(
          credentials.clientId,
          credentials.clientSecret,
          apiConfig.authBaseUrl,
          apiConfig.apiBaseUrl,
        )

      try {
        // Check API health
        println("Checking API health...")
        val isHealthy = service.healthCheck()
        println("API Health: ${if (isHealthy) "OK" else "FAILED"}")

        if (isHealthy) {
          // Get all locations
          println("\nFetching locations...")
          val locations = service.getLocations()

          println("Found ${locations.data.size} location(s):")
          locations.data.forEach { location ->
            println("  - Location ID: ${location.id}")
            location.attributes?.name?.let { println("    Name: $it") }
          }
        }
      } finally {
        // Always close the service
        service.close()
      }
    } catch (e: IllegalStateException) {
      System.err.println("Configuration Error: ${e.message}")
    } catch (e: Exception) {
      System.err.println("Error: ${e.message}")
      e.printStackTrace()
    }
  }
}

fun main() = runBlocking { App().run() }
