/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.justmejulian.gardena.mcp

import ch.justmejulian.gardena.mcp.server.MCPServer
import ch.justmejulian.gardena.mcp.util.Config
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.runBlocking

class App {
  private val logger = KotlinLogging.logger {}

  suspend fun run(args: Array<String>) {
    try {
      val transport = args.argValue("--transport") ?: "stdio"
      val port = args.argValue("--port")?.toIntOrNull() ?: 3000

      // Load credentials from environment variables
      val credentials = Config.loadGardenaCredentials()
      val apiConfig = Config.loadApiConfig()

      val mcpServer = MCPServer(apiKey = credentials.apiKey, apiBaseUrl = apiConfig.apiBaseUrl)

      logger.info { "Starting MCP server (transport=$transport)" }
      when (transport) {
        "sse" -> {
          // Bearer token is extracted per-session from the Authorization header — no token needed here
          mcpServer.runSse(port)
        }
        "stdio" -> {
          val bearerToken =
            args.argValue("--bearer-token")
              ?: throw IllegalStateException("--bearer-token <token> is required for stdio transport")
          mcpServer.runStdio(bearerToken)
        }
        else -> {
          logger.error { "Unknown transport '$transport'. Use 'stdio' or 'sse'." }
          return
        }
      }
    } catch (e: IllegalStateException) {
      logger.error { "Configuration error: ${e.message}" }
    } catch (e: Exception) {
      logger.error(e) { "Unexpected error" }
    }
  }
}

/** Returns the value following [flag] in the args array, or null if not present. */
private fun Array<String>.argValue(flag: String): String? {
  val idx = indexOf(flag)
  return if (idx >= 0 && idx + 1 < size) get(idx + 1) else null
}

fun main(args: Array<String>) = runBlocking { App().run(args) }
