/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    // Kotlin serialization plugin for JSON support
    kotlin("plugin.serialization") version "2.2.20"
    
    // ktfmt plugin for Kotlin code formatting
    alias(libs.plugins.ktfmt)
    
    id("org.openapi.generator") version "7.11.0"
    
    // Shadow plugin for creating fat JARs
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val ktorVersion = "3.2.0"
val jacksonVersion = "2.18.2"

dependencies {
    // Kotlin Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1")
    
    // Kotlin Serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    
    // MCP SDK
    implementation("io.modelcontextprotocol:kotlin-sdk:0.7.5")
    
    // SLF4J (logging)
    val slf4jVersion = "2.0.17"
    implementation("org.slf4j:slf4j-nop:$slf4jVersion")
    
    // Ktor Client
    implementation("io.ktor:ktor-client-cio:$ktorVersion")
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
    implementation("io.ktor:ktor-serialization-jackson:$ktorVersion")
    
    // Ktor Server (required by MCP SDK)
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-sse:$ktorVersion")
    
    // Jackson for JSON serialization (required by generated Java client)
    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion")
    
    // Dependencies for generated Java code
    implementation("org.openapitools:jackson-databind-nullable:0.2.6")
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")

    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ch.justmejulian.gardena.mcp.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

ktfmt {
    // Use Google style (default is Kotlinlang)
    googleStyle()
}

// OpenAPI Generator configuration for Gardena Smart System API
openApiGenerate {
    generatorName.set("java")
    inputSpec.set("$projectDir/src/main/resources/iapi-v2.yml")
    outputDir.set("$projectDir/src/main/java/com/gardena/smartgarden/service/iapi/generated")
    apiPackage.set("com.gardena.smartgarden.service.iapi.generated.api")
    modelPackage.set("com.gardena.smartgarden.service.iapi.generated.model")
    library.set("native")
    globalProperties.set(mapOf(
        "apiTests" to "false",
        "modelTests" to "false"
    ))
    configOptions.set(mapOf(
        "dateLibrary" to "java8",
        "useJakartaEe" to "true"
    ))
}

// Make Kotlin compilation depend on OpenAPI generation
tasks.named("compileKotlin") {
    dependsOn("openApiGenerate")
}

// Make ktfmt tasks depend on OpenAPI generation
tasks.named("ktfmtCheckMain") {
    dependsOn("openApiGenerate")
}

tasks.named("ktfmtFormatMain") {
    dependsOn("openApiGenerate")
}
