/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.justmejulian.gardena.mcp

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
  @Test
  fun `app can be instantiated`() {
    val classUnderTest = App()
    assertNotNull(classUnderTest, "app should be instantiated")
  }
}
